[project]
name = "ml-inference-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PSRahul", email = "psrahul.ml@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "celery[redis]>=5.6.3",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.13.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "redis>=8.1.0",
]

[project.scripts]
ml-inference-server = "ml_inference_server:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint="src.ml_inference_server.main:app"

[tool.pytest.ini_options]
pythonpath=["."]
